import { RoundedImage } from "@/components/RoundedImage"
import { Sidebar, SidebarItem } from "@/components/Sidebar"
import Image from "next/image"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return ( <div className="flex gap-20">
    <div className="flex-none">
      <Sidebar>
        <SidebarItem >
          <RoundedImage imagePath="/logo1.png" width={160} height={160} />
        </SidebarItem>
        <SidebarItem>Profile</SidebarItem>
      </Sidebar>
    </div>
      <div className="flex-grow">{children}</div>
  </div>
  )
}
