import { RoundedImage } from "@/components/RoundedImage"
import { Sidebar, SidebarItem } from "@/components/Sidebar"
import { IoPerson } from "react-icons/io5";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return ( <div className="flex gap-10">
    <div className="">
      <Sidebar>
        <div className="mt-10 mb-10" >
          <RoundedImage imagePath="/logo1.png" width={160} height={160} />
        </div>
        <SidebarItem>
        <IoPerson className="mr-4" />
          Profile
          </SidebarItem>
      </Sidebar>
    </div>
      <div className="flex mt-5">{children}</div>
  </div>
  )
}
