import { AvatarComp, RoundedImage } from "@/components/RoundedImage"
import { Sidebar, SidebarItem } from "@/components/Sidebar"
import { Avatar, AvatarImage } from "@/components/ui/avatar";
import { IoPerson } from "react-icons/io5";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return ( <div className="flex gap-10">
    <div className="">
      <Sidebar>
        <div className="flex items-center mt-10 mb-10" >
        <AvatarComp width={64} height={64} imagePath="/avatarferas.png"/>
        <div className="pl-5 text-white">Feras Ali Alhazmi</div>
        </div>
        <SidebarItem>
        <IoPerson className="mr-4" />
          Profile
          </SidebarItem>
      </Sidebar>
    </div>
      <div className="flex mt-5">{children}</div>
  </div>
  )
}
